version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=haseeb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fetlla
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static:
